### ISSUE TITLE
Callback on end is not working

### ISSUE THREAD

**Issue by gatoniel** [CSBDeep/CSBDeep#3]
Hi,

I got your code running. I changed all the keras imports to tensorflow.python.keras since we are using this version of keras. To log the metrics in a csv file I added a CSVLogger Callback in CARE.prepare_for_training (care_standard.py). I also added my own metrics in prepare_model (internals/train.py). I use the probabilistic model with an _sigmoid_ activation in the end. My files are in [https://github.com/gatoniel/CSBDeep/tree/working](https://github.com/gatoniel/CSBDeep/tree/working). I create the model with create_csbdeep.py and train it with train_csbdeep.py. After one epoch of training I get this error message:

> Traceback (most recent call last):
  File "../CSBDeep/train_csbdeep.py", line 82, in <module>
    main()
  File "../CSBDeep/train_csbdeep.py", line 76, in main
    history = model.train(X,Y, validation_data=(X_val,Y_val))
  File "/code/CSBDeep/csbdeep/models/care_standard.py", line 262, in train
    callbacks=self.callbacks, verbose=1)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training.py", line 1603, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/training_generator.py", line 240, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/callbacks.py", line 95, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/code/CSBDeep/csbdeep/utils/tf.py", line 269, in on_epoch_end
    val_data = list(v[:self.n_images] for v in self.validation_data)
  File "/code/CSBDeep/csbdeep/utils/tf.py", line 269, in <genexpr>
    val_data = list(v[:self.n_images] for v in self.validation_data)
TypeError: 'NoneType' object is not subscriptable

I don´t get exactly what is wrong here. Can you help me?

**Comment by uschmidt83** [comment]
Hi,

this error message comes from the `CARETensorBoard` callback (`csbdeep/utils/tf.py`, [line 269](https://github.com/gatoniel/CSBDeep/blob/working/csbdeep/utils/tf.py#L269)). Concretely, it seems to be caused by training the model without validation data.
To avoid this problem, try training with validation data or disable the callback (set `train_tensorboard = False` in the `Config`).

**Comment by gatoniel** [comment]
Thanks for the suggestions. I am going to try the recommended fixes.
